### ISSUE TITLE
Missing Temperature directory

### ISSUE THREAD

**Issue by rjanvier** [mergarsal/GNCSO#1]
Hello,
Thanks for Open Sourcing your code.
I tried it recently and I think a directory and some files are missing.
In the include/gncso/Smooth/gnc_smooth.h
https://github.com/mergarsal/GNCSO/blob/305870b88487a969a67dab0e91138229b04db3ab/include/gncso/Smooth/gnc_smooth.h#L15
the Temperature directory and the associated file are missing in the repository tree.
Thanks in advance.

**Comment by mergarsal** [comment]
That's correct. I just modified the line in the file.
That directory is still under development.

**Comment by rjanvier** [comment]
Thank you! Maybe you should update the submodule pointer in FastCertRelPose Repo (https://github.com/mergarsal/FastCertRelPose/tree/main/dependences) as well :)
